# Generated by Django 3.1.7 on 2021-04-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='participating',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
